src/globals.php

| Tests pass?   | ✔️/❌
The meaning of the function name "dd" is "dump and die". Also in many cases needs dump more than one variable

Fix 'dd' function conflicts with dependencies

---

composer.json
config/common.php
config/params.php
src/Controller.php
src/Entity/User.php
src/Repository/UserRepository.php

| Fixed issues  | #23 
Added Cycle ORM support  via `yii-cycle` package and configured;
`UserRepository` extends `Cycle\ORM\Select\Repository`
Some bugfixes

Added Cycle ORM support  via `yii-cycle` package and configured;

---

src/Parameters.php

improvement App\Parameters

---

composer.json

At now hiqdev/composer-config-plugin will write into our own `runtime` directory instead of `vendor/hiqdev/composer-config-plugin/composer-config-output`

Moved composer-config-output directory to our own `runtime` folder

---

public/index.php

Separate emitter from the Application

---

composer.json
src/Installer.php

When run application via docker-compose.yml Builder throw Exception due to insufficient access to runtime folder. This PR fix that

Fix access to runtime

---

src/Controller.php

`$controller` => `$self` .  just for replace keyword `this` to `self` for closure . reduce to think `$controller` may has other useful thing.
```
return $controller->renderContent($controller->view->render($view, $parameters, $controller));
```
=>
```
return $self->renderProxy($view, $parameters); 
```
// closure for proxy,use parent var. 
// reduce a level(hierarchy?) .
```
if ($layout === null) {
return $content;
}
```
// return early . reduce a thinking stack.

reconstruct App\Controller->render make it easy to understand.

---

composer.json
src/Blog/Archive/ArchiveRepository.php
src/Blog/Tag/TagRepository.php

Fix repositories for pgsql

---

config/params.php
config/routes.php
src/ViewInjection/LayoutViewInjection.php
views/layout/main.php

~~Currently leads to `Unprocessable entity`, need to find source and fix it.~~

Logout as POST request

---

config/web/application.php
src/Handler/NotFoundHandler.php
views/site/404.php

| Fixed issues  | #192 
no cats, sry :smile_cat:

Added 404 fallback page

---

composer.json

`yiisoft/http` used in routes configuration.

Add yiisoft/http to dependencies

---

src/Blog/Post/PostController.php
src/Contact/ContactController.php

Using DI for forms makes these stuck in the container thus causes issues in event-loop environments.

Do not use DI for forms

---

src/functions.php

Dump functions were moved to the `yiisoft/var-dumper` package:
https://github.com/yiisoft/var-dumper/blob/master/src/functions.php

Remove dump functions from this package

---

src/Contact/ContactController.php

Argument must be of type array.
`\Psr\Http\Message\ServerRequestInterface::getParsedBody` could be `null|object|array`

fix: Uncaught TypeError

---

composer.json

Added composer "serve" command - mentioned in README but missing from composer.json
| Is bugfix?    | No
| New feature?  | Yes
| Breaks BC?    | No

Added "serve" command

---

composer.json

Original faker library is not compatible with php 8 and it is not maintained anymore.
So I suggest to use maintained and compatible version.

Use new version of Faker

---

config/params.php
src/Command/Fixture/SchemaClearCommand.php
tests/Cli/ConsoleCest.php

Clear db during testing

---

composer.json

fix #474
https://github.com/symfony/console/commit/921378e9d9485dbeab330809b74b0aa50df0b7fc

fix: symfony/console 6.1.1 require php >8.1

---

src/Middleware/LocaleMiddleware.php

1. create host `127.0.0.1 kubernetes.docker.internal`
2. open http://kubernetes.docker.internal:8080/ru/ for RU language
3. Open http://kubernetes.docker.internal:8080/ 
RU language
default language EN
cookie _language missed
PS
Disabled Secure attribute of cookie for _language
https://web.dev/when-to-use-local-https/#use-http:localhost-by-default

Creating cookie _language for HTTP

---

src/Contact/views/contact/form.php

Added missed multipart/form-data
Added missed multiple name attribute
Closing DIV tag matches nothing

Uploading files via Contact form

---

src/Blog/Post/PostController.php

Change $form->getFirstErrors()  to $form->getFormErrors()
ERROR: UndefinedMethod - src/Blog/Post/PostController.php:58:44 - Method App\Blog\Post\PostForm::getFirstErrors does not exist (see https://psalm.dev/022)
$parameters['errors'] = $form->getFirstErrors();
| Fixed issues  | Change $form->getFirstErrors()  to $form->getFormErrors()

Psalm Level 6 Testing:

---

composer.json

| Fixed issues  |  To fix The process ".\yii serve" exceeded the timeout of 300 seconds.
P.S. see https://getcomposer.org/doc/06-config.md#process-timeout

fix: Timeout for ".\yii serve"

---

blog-api/config/common/routes.php
blog/config/common/routes/routes.php

https://github.com/yiisoft/yii-swagger/pull/79

Add cors for swagger

---

.github/workflows/blog-api_build.yml
.github/workflows/blog-api_dependency.yml
.github/workflows/blog-api_static.yml
.github/workflows/blog_build.yml
.github/workflows/blog_dependency.yml
.github/workflows/blog_static.yml
blog/.editorconfig
blog/.gitignore
blog/Makefile
blog/config/common/di/router.php
blog/config/web/events.php
blog/configuration.php
blog/package.json
blog/src/User/Controller/UserController.php

Blog: Fix locale, routes and npm dependencies

---

blog/composer.json
blog/resources/views/auth/login.php
blog/resources/views/signup/signup.php
blog/resources/views/user/index.php
blog/src/Auth/Controller/AuthController.php
blog/src/Auth/Controller/SignupController.php
blog/src/Auth/Form/LoginForm.php
blog/src/Auth/Form/SignupForm.php
blog/src/Blog/Post/PostController.php
blog/src/Blog/Post/PostForm.php
blog/src/Contact/ContactController.php
blog/src/Contact/ContactForm.php
blog/src/Contact/ContactMailer.php
blog/src/Contact/views/contact/form.php

Adapt to last changes in Yii DataView and Yii Form

---

blog/README.md
blog/config/common/params.php
blog/resources/views/user/index.php
blog/src/Auth/Controller/AuthController.php
blog/src/Blog/Archive/ArchiveController.php
blog/src/Blog/BlogController.php
blog/src/Blog/CommentController.php
blog/src/User/Controller/UserController.php
blog/src/Widget/OffsetPagination.php
blog/tests/Acceptance/LoginAcceptanceCest.php

Route attribute
