yiisoft/demo

- src/Controller/SiteController.php
> fix error "Return value must be of the type string, null returned"

- public/index.php
> Change 'app' to Application::class

- config/common.php
- src/Factory/LoggerFactory.php
> Add LoggerFactory

- config/common.php
- config/web.php
- src/Factory/ViewFactory.php
> Add alias in ViewFactory

- src/globals.php
> Fix VarDumper FQN

- src/Controller.php
> Replaced the variable with the getter method.

- src/Controller/ContactController.php
> ContectController fix mailer params

- src/Factory/AppRouterFactory.php
- src/Factory/ViewFactory.php
- views/auth/login.php
- views/contact/form.php
- views/layout/main.php
| Tests pass?   | ✔️/❌
Now we can generate urls to actions
> Added routes names and replaced static url to dynamic

- resources/mail/layouts/html.php
In order to make it better we should print app name, view title and character encoding but I don’t know how to make it in Yii3.
Yii2 equivalents:
* `<?= Html::encode(Yii::$app->name) ?>`
* `<?= Html::encode($this->title) ?>`
* `<?= Yii::$app->charset ?>`
> More verbose HTML mail layout

- src/Factory/MiddlewareDispatcherFactory.php
> Fix namespace of ErrorCatcher

- config/web.php
- src/Factory/MiddlewareDispatcherFactory.php
changes related to [this PR](https://github.com/yiisoft/yii-web/pull/198)
> SubFolderMiddleware renamed to SubFolder

- composer.json
- src/Asset/AppAsset.php
- src/Factory/ViewFactory.php
- views/layout/main.php
> Fix usage assets.

- src/Parameters.php
>  Fix support config with dot in key

- config/common.php
- config/params.php
- config/web.php
- src/Command/User/CreateCommand.php
- src/Controller.php
- src/Controller/AuthController.php
- src/Controller/ContactController.php
- src/Controller/SiteController.php
- src/Factory/LoggerFactory.php
- src/Factory/MailerFactory.php
- src/Factory/MiddlewareDispatcherFactory.php
- src/Factory/ViewFactory.php
- views/layout/main.php
> Clean and format

- src/Parameters.php
> Simplify parameters

- config/web.php
> Fix namespace import EventDispatcher

- README.md
otherwise no vendor directory will contain the server
| Tests pass?   | ✔️/❌
> add missing install step composer install

- src/Factory/AppRouterFactory.php
- src/Middleware/ApiDataWrapper.php
> Move data wrapper to ApiDataWrapper

- src/Factory/AppRouterFactory.php
> Cleanup AppRouterFactory

- config/web.php
> Remove GroupFactory

- config/common.php
> Change cache type

- src/Blog/Archive/ArchiveRepository.php
- src/Blog/Tag/TagRepository.php
> Fix repo comments

- composer.json
- public/index.php
> Add EventConfigurator to index.php

- src/Blog/Entity/Post.php
- src/Blog/Entity/Tag.php
- src/Entity/User.php
> Do not return ArrayCollection

- views/blog/post/index.php
> Fix post view error: call count on array

- config/params.php
> fix: yii serve gives error #102

- src/Entity/User.php
> getToken() never return null

- config/params.php
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/105
> Fix commans console.

- src/Provider/WebViewProvider.php
- views/layout/main.php
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/104
> Fix currentUrl.

- views/layout/main.php
> Fix #104 regression in getting current URL

- config/params.php
- src/Command/Fixture/AddCommand.php
- src/Command/User/CreateCommand.php
Changes related to https://github.com/yiisoft/yii-cycle/pull/38
> Update yii-cycle config

- composer.json
- public/index.php
| Is bugfix?    |
| New feature?  |
| Breaks BC?    |
| Tests pass?   |
> Move "EventConfiguration" to separate package

- config/web.php
- src/Blog/Archive/ArchiveController.php
- src/Blog/BlogController.php
- src/Blog/CommentController.php
- src/Blog/Post/PostController.php
- src/Blog/Tag/TagController.php
- src/Contact/ContactController.php
- src/Controller/AuthController.php
- src/Controller/SignupController.php
- src/Controller/SiteController.php
- src/Controller/UserController.php
- src/ViewRenderer.php
Container default config:
```php
\App\ViewRenderer::class => [
'__construct()' => [
'viewBasePath' => '@views',
'layout' => '@views/layout/main',
],
]
```
Controller example
```php
class SiteController
{
private ViewRenderer $viewRenderer;
public function __construct(ViewRenderer $viewRenderer)
{
$this->viewRenderer = $viewRenderer->withControllerName('site');
}
public function index(): ResponseInterface
{
return $this->viewRenderer->render('index');
}
}
```
or
```php
class SiteController
{
private ViewRenderer $viewRenderer;
public function __construct(ViewRenderer $viewRenderer)
{
$this->viewRenderer = $viewRenderer->withController($this);
}
public function …
```
> Add ViewRenderer

- config/providers-web.php
- config/web.php
| Fixed issues  | https://github.com/yiisoft/composer-config-plugin/pull/116
> Use require instead of variable

- public/js/app.js
- src/Blog/Entity/Post.php
- src/Blog/Post/PostController.php
- views/blog/post/__form.php
> Creating tags, adding/removing tags from posts

- views/blog/comments/_comments.php
> Fix comments bug

- src/Blog/Archive/ArchiveController.php
> Added explicit casting for year and month in ArchiveController

- composer.json
- config/routes.php
- src/Controller/ApiInfo.php
- views/layout/main.php
> Add swagger service

- config/console.php
| Related PR  | https://github.com/yiisoft/aliases/pull/21
> Remove aliases config

- config/web.php
| Related PR  | https://github.com/yiisoft/validator/pull/82
> Removed validator config

- src/Blog/Widget/PostCard.php
- src/Widget/OffsetPagination.php
> Hotfix error `Class 'Yiisoft\Yii\Bootstrap4\Html' not found`

- composer.json
- config/web.php
> Replace PSR-7 with httpsoft

- config/routes.php
- src/Blog/Entity/Post.php
> Setting Post title/content in constructor - #156

- public/index.php
| Fixed issues  | https://github.com/yiisoft/yii-web/issues/309
| Depends on | https://github.com/yiisoft/yii-web/pull/325, https://github.com/yiisoft/yii-web/pull/326
> Move out error handler from application

- composer.json
> Remove npm.

- src/Command/Router/ListCommand.php
Merge after https://github.com/yiisoft/router/pull/77 and https://github.com/yiisoft/router-fastroute/pull/43
> Fix router ListCommand

- config/common/router.php
- src/ViewInjection/LayoutViewInjection.php
Merge after https://github.com/yiisoft/router-fastroute/pull/44 and https://github.com/yiisoft/router/pull/78
> Change way to get current URI in LayoutInjection

- config/params.php
> Add assets aliases

- composer.json
- config/common/rbac.php
- config/params.php
Need merge after release `yiisoft/aliases:1.1.0`
> Prepare to yiisoft/aliases:^1.1.0

- composer.json
- config/web/middleware-dispatcher.php
- public/index.php
> Add error handler from separated package instead of yii-web

- config/params.php
> Fix unsed params.

- config/providers-web.php
- config/providers.php
> Fix config console.

- config/routes.php
> Add Html response fermatter for Swagger

- composer.json
- src/Blog/BlogController.php
- src/Controller/AuthController.php
- src/Service/UserService.php
- src/ViewInjection/LayoutViewInjection.php
| Fixed issues  | https://github.com/yiisoft/yii-web/pull/334
> Switch to user package

- public/index.php
| Fixed issues  | https://github.com/yiisoft/yii-console/pull/89
> Serve existing files directly by PHP built-in server

- views/contact/form.php
- views/layout/main.php
| Fixed issues  | https://github.com/yiisoft/widget/pull/22
> Add support immutable widget.

- .github/workflows/build.yml
- .scrutinizer.yml
- public/index-test.php
> Move C3.php to index-test.php

- src/Blog/Post/PostController.php
- src/Contact/ContactController.php
- src/Controller/AuthController.php
- src/Controller/SignupController.php
See https://github.com/yiisoft/yii-demo/pull/185
> Remove explicit use of CSRF in controllers

- src/ViewInjection/LayoutViewInjection.php
- views/layout/main.php
> Fix #188 Menu items never activated

- src/Blog/Archive/ArchiveRepository.php
- src/Blog/Comment/CommentRepository.php
- src/Blog/Post/PostRepository.php
- src/Blog/Tag/TagRepository.php
- src/User/Controller/ApiUserController.php
- src/User/Controller/UserController.php
| Fixed issues  | https://github.com/yiisoft/data/pull/66
> Specify Sort fields

- composer.json
- public/index.php
- public/js/app.js
- src/Asset/AppAsset.php
- src/Blog/Widget/PostCard.php
- src/Service/WebControllerService.php
- src/Widget/OffsetPagination.php
- views/auth/login.php
- views/blog/_archive.php
- views/blog/_topTags.php
- views/blog/archive/monthly-archive.php
- views/blog/archive/yearly-archive.php
- views/blog/index.php
- views/blog/post/__form.php
- views/blog/post/index.php
- views/blog/tag/index.php
- views/contact/form.php
- views/layout/main.php
- views/signup/signup.php
- views/site/index.php
- views/user/index.php
Requires ~~https://github.com/yiisoft/yii-bootstrap5/pull/21~~
> Upgrade to Bootstrap 5

- views/layout/main.php
| Fixed issues  | Requires https://github.com/yiisoft/assets/pull/33 and https://github.com/yiisoft/view/pull/114
> AssetManager - jsString & jsVar

- views/blog/_archive.php
- views/blog/_topTags.php
> fixed bug where param for Html::span was int

- views/layout/main.php
This code works, but is ugly. Anyone got something better?
> Activate menu items on every subpage as well

- views/auth/login.php
- views/blog/_archive.php
- views/blog/_topTags.php
- views/blog/post/__form.php
- views/signup/signup.php
| Related PR  | #197 
Bootstrap migrating to v5: https://getbootstrap.com/docs/5.0/migration/#forms-2
> Bootstrap5 adjustments

- config/web/application.php
- resources/mail/contact.php
- src/Contact/ContactController.php
- src/Contact/ContactMailer.php
- src/Widget/FlashMessage.php
- tests/Acceptance/ContactPageCest.php
- tests/Functional/ContactCest.php
- views/contact/form.php
> FlashMessage

- resources/asset/js/app.js
> better string template

- src/Controller/AuthController.php
> Fix User enumeration vulnerability

- src/Asset/AppAsset.php
> Fix AppAsset

- src/Command/Fixture/AddCommand.php
| Fixed issues  | https://github.com/yiisoft/yii-cycle/issues/91
> Fix yiisof#91: XDebug max nesting level error

- src/Blog/Archive/ArchiveRepository.php
- src/Blog/Comment/CommentRepository.php
- src/Blog/Post/PostRepository.php
- src/Blog/Tag/TagRepository.php
- src/Command/Fixture/AddCommand.php
- src/Controller/SignupController.php
- src/User/Console/CreateCommand.php
- src/User/UserRepository.php
- views/site/index.php
Sync code with https://github.com/yiisoft/yii-cycle/pull/90
> Use EntityReader and EntityWriter

- src/User/UserRepository.php
| Fixed issues  | yiisoft/user#3
> Remove findIdentityByToken from UserRepository

- src/ViewInjection/LinkTagsViewInjection.php
- src/ViewInjection/MetaTagsViewInjection.php
- views/layout/main.php
> Fix html validation errors

- src/Blog/Post/PostController.php
- src/Blog/Post/PostForm.php
- src/Contact/ContactController.php
> Fix changes of yiisoft/form

- config/common/logger.php
> Add logger configuration by default

- src/Contact/ContactForm.php
- views/contact/form.php
| Related issues  | https://github.com/yiisoft/form/issues/65
> Add html options

- src/Blog/Archive/ArchiveRepository.php
- src/Blog/Comment/CommentRepository.php
- src/Blog/Post/PostRepository.php
- src/Blog/Tag/TagRepository.php
- src/User/Controller/ApiUserController.php
- src/User/Controller/UserController.php
Use `Sort::any` and `Sort::only` instead of `new Sort`
> Change Sort to have two static constructors

- src/Contact/ContactMailer.php
> Fix ContactMailer due to yiisoft/mailer changes

- config/web/application.php
- public/index-test.php
- public/index.php
Waiting: https://github.com/yiisoft/error-handler/pull/25
> Fix config due to yiisoft/error-handler changes

- README.md
- public/index.php
My first init Yii3 app send me on page with An internal server error occurred and nothing else
Not very friendly :)
> build: settings for initial launch

- resources/mail/layouts/html.php
- views/auth/login.php
- views/blog/post/__form.php
- views/contact/form.php
- views/signup/signup.php
Many tools expect correct syntax
https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/var.html
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#517-var
https://www.jetbrains.com/help/phpstorm/php-non-canonical-order-of-elements.html
https://phpstan.org/writing-php-code/phpdocs-basics
> docs: Non-canonical order of @var

- src/Blog/Post/PostController.php
- src/Blog/Post/PostForm.php
- src/Blog/Widget/PostCard.php
- src/Contact/ContactController.php
- src/Contact/ContactForm.php
- src/Widget/OffsetPagination.php
- views/blog/_archive.php
- views/blog/_topTags.php
- views/blog/archive/index.php
- views/blog/archive/yearly-archive.php
- views/blog/post/index.php
- views/blog/tag/index.php
- views/user/index.php
Adopt to https://github.com/yiisoft/html/pull/52
> Adopt to yiisoft/html PR #52

- src/Blog/BlogController.php
- src/Controller/AuthController.php
- src/User/UserService.php
- src/ViewInjection/LayoutViewInjection.php
See https://github.com/yiisoft/user/pull/24
> Adopt to yiisoft/user PR #24

- src/Blog/Widget/PostCard.php
> Fix #248 Incorrect return type

- src/ApplicationRunner.php
- tests/Functional/EventListenerConfigurationTest.php
| Fixed issues  | ❌
Won't work without yiisoft/yii-event#22 merged
> Add event listener checker

- .github/workflows/static.yml
- composer.json
SQLite extension is required to run demo app, so the extension must be set as dependency.
| Is bugfix?    | Yes
| New feature?  | No
| Breaks BC?    | No
> Added SQLite dependency to composer.json

- README.md
- config/packages/yiisoft/middleware-dispatcher/config/dist/web.php
- config/packages/yiisoft/middleware-dispatcher/config/web.php
- views/site/index.php
- yii
- yii.bat
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/112
> Move console entry point to application

- src/Blog/Widget/PostCard.php
- views/blog/_archive.php
- views/blog/archive/index.php
- views/blog/post/index.php
If create post and not publish him, then appears errors in blog.
> Fix errors on unpublished posts

- README.md
| Fixed issues  | #253
Updating logo in `README.md` for a transparent one.
> #253 - Updating logo for the yii-logo-light in README.md

- yii.bat
| Is bugfix?    | ✔
See https://github.com/yiisoft/yii-dev-tool/pull/138
> Remove ".exe" from PHP_COMMAND

- config/packages/yiisoft/yii-view/dist/params.php
- config/packages/yiisoft/yii-view/dist/web.php
- config/params.php
| Fixed issues  | https://github.com/yiisoft/yii-view/pull/26
> Add the ability to specify an aliases for the layout.

- config/packages/yiisoft/profiler/common.php
| Fixed issues  | Update config to profiler changes
> Update profiler config

- config/packages/yiisoft/profiler/common.php
\Yiisoft\Profiler\Target\AbstractTarget::enable() is void
Fixed tests
> fix: profiler/config

- views/layout/main.php
@see https://github.com/yiisoft/view/pull/145 and https://github.com/yiisoft/assets/pull/68
> Adopt to new yiisoft/view and yiisoft/assets

- views/layout/main.php
Adopt to https://github.com/yiisoft/view/pull/153
> Adopt to new yiisoft/view

- config/packages/yiisoft/view/params.php
| Fixed issues  | https://github.com/yiisoft/view/issues/156
Waiting: https://github.com/yiisoft/view/pull/157
> Update view config params due to yiisoft/view changes

- .github/workflows/dependency.yml
- composer.json
> Remove dependencie innecesary composer.json.

- composer.json
> Simplify config in composer.json via using `source-directory` option

- src/Contact/ContactForm.php
see https://github.com/yiisoft/validator/pull/134
> Adopt to new yiisoft/validator

- composer.json
- config/packages/yiisoft/yii-debug-api/params.php
- config/packages/yiisoft/yii-debug/params.php
> Add Debug Viewer

- src/Blog/Post/PostForm.php
> Fix post form

- src/Command/Router/ListCommand.php
- views/layout/main.php
> Adjust to yiisoft/router changes

- .editorconfig
- .github/workflows/build.yml
- .github/workflows/dependency.yml
- .github/workflows/static.yml
- .scrutinizer.yml
- README.md
- composer.json
> Raise minimum PHP requirements to ^8.0 and yiisoft/aliasess to ^2.0

- views/layout/main.php
| Fixed issues  | Adopt yiisoft/router#110
> Adjust to router changes

- src/Command/Router/ListCommand.php
> Adjust router/list command

- src/Contact/ContactController.php
> Fix ContactController due yiisoft/yii-view package changes

- docker-compose.yml
> Raise PHP version to 8.0  for docker image

- composer.json
- config/bootstrap.php
- config/packages/yiisoft/yii-debug/params.php
- src/ApplicationRunner.php
> New providers

- composer.json
> Hotfix typo

- composer.json
- config/bootstrap-console.php
- config/bootstrap-web.php
- src/ApplicationRunner.php
- yii
> Fix bootstrap

- README.md
- public/index-test.php
- public/index.php
- src/ApplicationRunner.php
- tests/Functional/EventListenerConfigurationTest.php
- yii
| Fixed issues  | https://github.com/yiisoft/config/pull/73
> Adjust config

- src/User/Console/AssignRoleCommand.php
- src/User/Console/CreateCommand.php
> refactor: added NULL checks

- composer.json
- config/common/logger.php
- config/packages/dist.lock
- config/packages/merge_plan.php
- config/packages/yiisoft/assets/web.php
- config/packages/yiisoft/csrf/web.php
- config/packages/yiisoft/mailer-swiftmailer/common.php
- config/packages/yiisoft/view/common.php
- config/packages/yiisoft/view/params.php
- config/packages/yiisoft/view/web.php
- config/packages/yiisoft/yii-console/console.php
- config/packages/yiisoft/yii-view/params.php
- config/web/application.php
> Adopt to `yiisoft/definitions`

- yii
> Improve console entry point

- composer.json
- config/delegates-console.php
- config/delegates-web.php
- config/delegates.php
- config/packages/dist.lock
- config/packages/merge_plan.php
- src/Runner/ConsoleApplicationRunner.php
- src/Runner/WebApplicationRunner.php
- yii
| Fixed issues  | related to https://github.com/yiisoft/di/pull/250
> Add delegates config

- public/index.php
| Fixed issues  | Serving static files with query string
> Fix built-in server routing

- composer.json
- config/packages/yiisoft/view/params.php
- config/packages/yiisoft/yii-view/params.php
- src/ViewInjection/CommonViewInjection.php
- src/ViewInjection/ContentViewInjection.php
Adopt to https://github.com/yiisoft/view/pull/184 and https://github.com/yiisoft/yii-view/pull/43
> Adopt to new `yiisoft/view` and `yiisoft/yii-view`

- src/Blog/Post/PostForm.php
- src/Contact/ContactForm.php
- src/Contact/views/contact/form.php
- src/Widget/LanguageSelector.php
- tests/Acceptance/ContactPageCest.php
- tests/Functional/ContactCest.php
- views/layout/main.php
> Enhacements.

- config/routes.php
- src/Blog/Post/PostRepository.php
> Fix errors on opening the page's page

- composer.json
- views/layout/main.php
Waiting: https://github.com/yiisoft/assets/pull/88
> Upgrade the yiisoft/assets version to 2.0

- config/routes.php
- config/web/application.php
| Fixed issues  | https://github.com/yiisoft/middleware-dispatcher/issues/43
> Adopt to middleware-dispatcher changes

- .scrutinizer.yml
- public/index.php
> Fix scrutinizer-ci and code-coverage.

- composer.json
- config/routes.php
Waiting: https://github.com/yiisoft/yii-middleware/pull/1
> Replace usage of yiisoft/yii-web to yiisoft/yii-http

- .github/workflows/build.yml
See https://github.com/shivammathur/setup-php#force-update-setup
> Force use latests PHP version in build workflow

- config/routes.php
- src/Blog/Archive/ArchiveController.php
- src/Blog/BlogController.php
- src/Blog/CommentController.php
- src/Blog/Post/PostController.php
- src/User/Controller/ApiUserController.php
- src/User/Controller/UserController.php
:warning: Merge after https://github.com/yiisoft/router/pull/128
> Adopt router changes

- composer.json
> Use stable version of yiisoft/mailer-symfony package

- config/routes.php
> Replace non existent method getParameter() on getArgument() 

- src/Blog/Archive/ArchiveController.php
- src/Blog/Post/PostController.php
- src/Blog/Tag/TagController.php
> Use current route interface instead of request

- src/Auth/Controller/AuthController.php
- src/Auth/Controller/SignupController.php
> Improve auth controllers

- tests/Functional/EventListenerConfigurationTest.php
| Fixed issues  | https://github.com/yiisoft/di/pull/276
> Adopt to DI changes

- config/web/auth.php
Waiting: https://github.com/yiisoft/user/pull/46
> Define current user configuration to web/auth config

- config/params.php
Waiting: https://github.com/yiisoft/user/pull/49
> Fix params configuration due yiisoft/user changes

- composer.json
> Use stable versions of yiisoft/translator-extractor

- src/Auth/AuthService.php
- src/Auth/Controller/AuthController.php
- src/Auth/Form/LoginForm.php
- src/Auth/Identity.php
Waiting: https://github.com/yiisoft/user/pull/51
> Update auth functionality due yiisoft/user changes

- tests/Functional/EventListenerConfigurationTest.php
| Fixed issues  |  -
Waiting:
https://github.com/yiisoft/yii-runner/pull/6
https://github.com/yiisoft/yii-runner-http/pull/13
https://github.com/yiisoft/yii-runner-console/pull/11
> Update EventListenerConfigurationTest due improve ConfigFactory::create()

- config/params.php
- src/Blog/Archive/ArchiveController.php
- src/Blog/BlogController.php
- src/Blog/CommentController.php
- src/Blog/Post/PostController.php
- src/Blog/Tag/TagController.php
- src/User/Controller/ApiUserController.php
- src/User/Controller/UserController.php
- views/layout/main.php
- views/site/404.php
https://github.com/yiisoft/router/pull/138
> Adapt to router changes

- views/layout/main.php
> Fix error on generate URL for change language

- .github/workflows/dependency.yml
> Fix dependency checker

- config/common/router.php
- src/Middleware/LocaleMiddleware.php
- views/layout/main.php
Merge after:
https://github.com/yiisoft/router/pull/156
https://github.com/yiisoft/router-fastroute/pull/94
> New locales based on pattern

- src/Middleware/LocaleMiddleware.php
> Fix redirect bug

- src/Middleware/LocaleMiddleware.php
Merge after https://github.com/yiisoft/router-fastroute/pull/97
> Remove default locale from generated url

- config/params.php
- config/routes.php
- src/User/Controller/ApiUserController.php
See https://github.com/yiisoft/yii-swagger/pull/48
> Adapt to yii-swagger changes

- config/params.php
- config/widgets.php
- src/Auth/Form/LoginForm.php
- src/Auth/Form/SignupForm.php
- src/Contact/views/contact/form.php
- views/auth/login.php
- views/layout/main.php
- views/signup/signup.php
> Update last changes `yiisoft/form`.

- .github/workflows/build.yml
- .github/workflows/dependency.yml
- .github/workflows/static.yml
- composer.json
> Add PHP 8.1 support to GitHub workflow, update dev-dependencies

- config/common/rbac.php
- src/User/Console/AssignRoleCommand.php
- src/User/Console/CreateCommand.php
| Fixed issues  | merge after https://github.com/yiisoft/rbac/pull/114
> Adjust to RBAC changes

- config/common/router.php
> Add debug toolbar

- config/common/router.php
> Don't add toolbar middleware in production

- composer.json
- config/params.php
- config/widgets.php
- src/Auth/Form/LoginForm.php
- src/Blog/Entity/Post.php
- src/Command/Fixture/AddCommand.php
- src/Contact/views/contact/form.php
- tests/Acceptance/ContactPageCest.php
- tests/Acceptance/LoginAcceptanceCest.php
- tests/Acceptance/SignupAcceptanceCest.php
- tests/Functional/ContactCest.php
- views/auth/login.php
- views/layout/main.php
- views/signup/signup.php
Adopt to https://github.com/yiisoft/form/pull/192
> Adopt to big refactoring of forms

- config/web/application.php
> Simplify config of `Application` class

- composer.json
- config/common/router.php
> Add debugger

- .env.example
- composer.json
- config/.merge-plan.php
- config/common/sentry.php
- config/params.php
Related: https://github.com/yiisoft/yii-sentry/pull/12
> Add yii-sentry

- src/Command/Router/ListCommand.php
> Fix router command

- composer.json
> Fix `yii-cycle` version

- config/.gitignore
Related to https://github.com/yiisoft/config/issues/121
> Remove incorrect comment in .gitignore

- src/Command/Router/ListCommand.php
> Improved view of router/list output

- composer.json
- config/params.php
> Update yii-sentry package

- src/Contact/views/contact/form.php
> Localization of contract form buttons

- config/common/translator.php
> Fix translator config

- composer.json
- phpunit.xml.dist
> Fix tests run

- src/Command/Fixture/AddCommand.php
| Fixed issues  | https://github.com/yiisoft/demo/issues/547
> Add fixture: add log caught error, fix 'rand' error

- blog-api/tests/Acceptance.suite.yml
- blog-api/tests/Functional.suite.yml
- blog/tests/Acceptance.suite.yml
- blog/tests/Functional.suite.yml
I've changed it because it's impossible to have at the time both a run dev server and a run test server.
Also it's impossible to run tests from `yii-debug-api`.
> Change test server port

- blog-api/config/prod/params.php
- blog-api/config/test/params.php
- blog/config/prod/params.php
- blog/config/test/params.php
> Disable yii-debug on specific environments

- blog-api/config/params.php
- blog/config/params.php
> Ignore inspector requests

- blog-api/config/common/validator.php
- blog/config/common/validator.php
> Adapt to last changes in validator

- blog-api/src/Queue/UserLoggedInMessage.php
> Fix missing method

- blog-api/composer.json
- blog-api/config/common/bootstrap.php
- blog-api/config/common/params.php
- blog-api/config/web/di/application.php
- blog/composer.json
- blog/config/common/bootstrap.php
- blog/config/common/params.php
- blog/config/web/di/application.php
- blog/config/web/params.php
⚠️  https://github.com/yiisoft/yii-middleware/pull/36
> Adapt `SubFolder` middleware changes

- ansible/roles/certbot/tasks/update_certificates.yml
- blog-api/config/web/di/application.php
- blog-api/src/Auth/AuthController.php
- blog-api/src/Auth/AuthRequest.php
- blog-api/src/Blog/BlogController.php
- blog-api/src/Blog/EditPostRequest.php
- blog-api/src/Blog/PostFormatter.php
- blog-api/src/Dto/ApiResponseData.php
- blog-api/src/Formatter/PaginatorFormatter.php
- blog-api/src/InfoController.php
- blog-api/src/User/UserController.php
- blog-api/src/User/UserFormatter.php
- blog/config/common/routes/routes.php
- blog/src/Controller/Actions/ApiInfo.php
- blog/src/User/Controller/ApiUserController.php
> Set up crontab for certbot renew

- .github/workflows/blog-api_build.yml
- .github/workflows/blog_build.yml
- blog-api/.env.test
- blog-api/tests/Acceptance.suite.yml
- blog-api/tests/Functional.suite.yml
- blog-api/tests/Functional/IndexControllerTest.php
- blog/.env.test
- blog/src/Auth/Form/LoginForm.php
- blog/src/Auth/Form/SignupForm.php
- blog/src/Contact/ContactForm.php
- blog/tests/Acceptance.suite.yml
- blog/tests/Functional.suite.yml
> Fix working directory for blog build

- blog-api/config/web/di/application.php
- blog/config/web/di/application.php
> Adapt to last changes in `Locale` middleware

- blog-api/composer.json
> update irc link

- blog-api/composer.json
- blog-api/config/common/params.php
- blog-api/config/web/di/application.php
- blog/composer.json
- blog/config/web/di/application.php
- blog/config/web/params.php
> :warning: Depends on https://github.com/yiisoft/yii-debug-api/pull/113.
> Sync with middleware

- blog/composer.json
> Fix `yiisoft/form` version

- blog/config/common/params.php
> Adapt to last changes in `yiisoft/form`

- blog/src/Blog/CommentController.php
- blog/tests/Acceptance/BlogPageCest.php
> fix blogcest

- blog/resources/views/layout/main.php
> Fix layout param

- blog-api/config/common/params.php
- blog/config/web/params.php
> Ignore locale middleware for gii controllers

- .github/workflows/blog-api_build.yml
- .github/workflows/blog-api_dependency.yml
- .github/workflows/blog-api_static.yml
- .github/workflows/blog_build.yml
- .github/workflows/blog_dependency.yml
- .github/workflows/blog_static.yml
- blog-api/composer.json
- blog-api/composer.lock
- blog/composer.json
- blog/composer.lock
> Use PHP 8.3

- blog-api/docker-compose.yml
- blog/docker-compose.yml
> Fix PHP docker image version
